/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyRatingComponent {
        "color": string;
        "maxstars": number;
        "rating": number;
    }
}
declare global {
    interface HTMLMyRatingComponentElement extends Components.MyRatingComponent, HTMLStencilElement {
    }
    var HTMLMyRatingComponentElement: {
        prototype: HTMLMyRatingComponentElement;
        new (): HTMLMyRatingComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-rating-component": HTMLMyRatingComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyRatingComponent {
        "color"?: string;
        "maxstars"?: number;
        "rating"?: number;
    }
    interface IntrinsicElements {
        "my-rating-component": MyRatingComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-rating-component": LocalJSX.MyRatingComponent & JSXBase.HTMLAttributes<HTMLMyRatingComponentElement>;
        }
    }
}
